### ISSUE TITLE
Multiple clicks on show performance shows multiple labels instead of one

### ISSUE THREAD

**Issue by Badhi** [Juhi004/fakeNewsDetector#2]
Steps to recreate :

Select Performance of the algorithm
Select Show Performance multiple times

Expected : 

Show the performance parameters on the same label over writing the existing values

Actual : 

multiple texts boxes appear below the previous text box lengthening the window

![mutliple_performances](https://user-images.githubusercontent.com/10277051/59620682-173d9f80-914b-11e9-9bb1-326feb600c1f.PNG)

**Comment by Juhi004** [comment]
Solved the problem.
